# Design and Train an object detector to detect objects

You have to design and implement a Training Pipeline that can train, test and visualize the model using the dataset provided.

## Assignment Protocols

- We expect it to take ~4 hours, with an extra 15 min for clear loom explanation(s)
  - The assessment is timeboxed at 5 hours total in a single block. So please plan accordingly
- You need to use Google Collaboratory to run and edit this notebook
- You can only use Python as a programming Language
- You cannot take help from any other person
- You can use Google to search for references
- You can not search on google for design-related things, like what should be loss function, or what should be model architecture.
  - But you can use pre-trained backbones from PyTorch
- Record a 5-10 mins of code walkthrough of the work you have done. You can use Loom Platform (https://www.loom.com) to record the video.
  - Design Decisions
    - Model Design which layers and activation functions you used and why
    - Loss function, which loss functions you used and why
    - Metrics, which metrics and why
  - Any optimizations you have made to the codebase
  - How you implemented resume functionality, what were the things you thought would be needed to resume training from exact same point
  - Explain what parts of the assessment are completed and what is missing?
  - Make sure to submit the screen recording link in the submission after you are done recording
  - Please note that the free plan on Loom only allows for videos up to 5 minutes in length. As such, you may need to record two separate 5-minute videos.
- [NO SUBMISSION WILL BE ACCEPTED WITHOUT]
  - Trained best model weights
  - Visualize Function in the Notebook
  - Code Walk-through video

## Task Details
Design a Training Pipeline to train a object detector with following specs or assumptions:
- Implement & Design Model
  - You can use any backbone
    - Either from PyTorch (torhvision) or any resource online
    - But you need to design head your self (head means how you will use features of the back bone and get the desired outputs)
  - Model needs to detect one object in each image
  - Model should output following for each image passed as input:
    - Whether we have an object or not
    - Where is the object?
      - The bounding box output format should be xmin, ymin, xmax, ymax
      - It is not necessary the model is trained to output exactly this format but the visualize function which shows output should output in this format
    - Either the object is a cat or dog?
    - And which specie the object belongs to? There are in total 9 species: 
      - Cat [3 species]:
        - Abyssinian
        - Birman
        - Persian
      - Dog [6 species]
        - american_bulldog
        - american_pit_bull_terrier
        - basset_hound
        - beagle
        - chihuahua
        - pomeranian
- Implement Custom Dataloader
  - This is obvious as dataset is in a unique format any predifined dataloader wont work
  - Follow best practices of writing custom dataloaders
  - Details of the format of the dataset are defined in the Dataset Details section below
  - Add needed pre-processing that you think would help train a better model or would help as we are using pre-trained weights as starting point
  - Add augmentations that you think would help train a better model
- Implement Loss Function
  - Design and implement a loss function that can handle all of the outputs we have
  - You can use pytorch built-in loss functions
  - There are many scenarios which you need to handle, which one can understand from the dataset details and the model design
- Implement Test Function
  - The test function should be able to run the model on the validation set and output the metrics for all the outputs of the model
  - Select the metrics carefully, there are many scenarios which can change the selection of a metric
  - Keep in mind there are multiple outputs, you would need a metric for each output
  - [NOTE] You don't need to implement metrics for the bounding box output as it can take more time than provided for this assessment. But please add details of the metrics you would have implemented in your code-walk through loom video.
- Update Resume Training Functionality using the best weights
  - Current script does not have save best weights functionality
  - The code should be able to resume training from exactly same point from where the training was stopped if model weights file is passed
  - Keep in mind you can not resume training from same point by just loading weights of the model
- Implement a visualize function [Most important, without this no submission will be accepted]
  - The input of the function should be path of a folder with images and the weight file
    - Also the output folder path to save outputs
  - This function should return a dictionary of dictionaries with following details for each image:
    - {
        "has_object": True,
        "cat_or_dog": "cat",
        "specie": "persian",
        "xmin": 10,
        "ymin": 10,
        "xmax": 10,
        "ymax": 10
    }
  - And in case there is no object it should have 0 for bbox values, "NA" for "cat_or_dog" and "specie", and False for "has_object".
  - Values of the returned dictionary should be like explained above and keys should be image names including the extension ".jpg" or ".jpeg"
  - Should save output image with bounding box drawn on it, with same name input image but place in the output folder 
- Try to train the best model


## Dataset Details
The dataset has in total 1041 images. Each image has a single object which is either a cat or a dog.
- There are multiple species for both cat and dog.
- The number of images falling in each specie is as follows:
  - basset_hound: 93
  - Birman: 93
  - pomeranian: 93
  - american_pit_bull_terrier: 93
  - american_bulldog: 93
  - Abyssinian: 92
  - beagle: 93
  - Persian: 93
  - chihuahua: 93
  - empty: 142
- The dataset has two folders:
  - images
    - Inside images folder we have 986 images in .jpg folder
  - labels
    - Inside labels folder we have 899 .xml files each file with details of image labels
    - For any image that does not have a cat or dog, there is no corresponding xml file

## Deliverable
- Updated Colab Based Jupyter Notebook:
  - With all the required functionality Implemented
  - Which one can train the model without any errors
  - One should achieve same metrics (Almost same metrics) if I run training using this collab notebook
    - Set default values for everything accordingly in the notebook
  - During evaluation we will just run the notebook and use the best weights the notebook saves automatically
- Best weights you have trained
  - We will Evaluate your weights against hold-out test we have and compare results
  - We will use visualize function to generate outputs for each image
  - Upload weights in an easily downloadable location like, Dropbox, Google Drive, Github, etc
- A video code-walk through explaining your design decisions including but not limited to:
  - Model Design which layers and activation functions you used and why
  - Loss function, which loss functions you used and why
  - Metrics, which metrics and why
  - Any optimizations you have made to the codebase
  - How you implemented resume functionality, what were the things you thought would be needed to resume training from exact same point


## Evaluation Criteria
 - Design Decisions
 - Completeness: Did you include all features?
 - Correctness: Does the solution (all deliverables) work in sensible, thought-out ways?
 - Maintainability: Is the code written in a clean, maintainable way?
 - Testing: Is the solution adequately tested?
 - Documentation: Is the codebase well-documented and has proper steps to run any of the deliverables?

## Extra Points
- Add metrics for the Bounding Box Output
- Any Updates in the notebook (Bugs/Implementation Mistakes etc)

## How to submit
- Please upload the Notebook for this project to GitHub, and post a link to your repository below [repo link box, on the left of submit button].
  - Create a new GitHub repository from scratch
  - Add the final Colab/Jupyter notebook to the repository
- Please upload video and your final best weights on Google Drive or any other platform, and paste the link to the folder with both video and model in the text box just above the submit button.
- Please paste the commit Id of the latest commit of your Github Repo, which should not be later than 5 hours of time when the repo was created.
  - Please note the submission without the commit id will not be considered.

# Install Required Modules

In [ ]:
! pip install bs4 lxml kaggle torchmetrics tqdm

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


# Download Dataset from Kaggle

In [ ]:
import os
os.environ['KAGGLE_USERNAME'] = 'bilalyousaf0014'
os.environ['KAGGLE_KEY'] = '11031bc21c5e3ec23585dbe17dc4267d'

In [ ]:
!kaggle datasets download -d bilalyousaf0014/ml-engineer-assessment-dataset

ml-engineer-assessment-dataset.zip: Skipping, found more recently modified local copy (use --force to force download)


In [ ]:
! unzip /content/ml-engineer-assessment-dataset.zip

Archive:  /content/ml-engineer-assessment-dataset.zip
replace assessment_dataset/images/00001.jpeg? [y]es, [n]o, [A]ll, [N]one, [r]ename: 

# MODEL IMPLEMENTATION:

In [74]:
import os
import torch
import torch.nn as nn
import numpy as np

from torchvision.models import resnet18, ResNet18_Weights

In [75]:
class Model(nn.Module):

  def __init__(self, load_state=None):
    super(Model, self).__init__()
    pretrained_model = resnet18(weights=ResNet18_Weights.DEFAULT)
    self.backbone = nn.Sequential(*list(pretrained_model.children())[:-2])
    
    ### Initialize the required Layers
    self.have_object = nn.Sequential(nn.Flatten(), nn.Linear(512, 256), nn.LeakyReLU(), nn.Linear(256, 128), nn.LeakyReLU(), nn.Linear(128, 1)) 
    self.cat_or_dog = nn.Sequential(nn.Flatten(), nn.Linear(512, 256), nn.LeakyReLU(), nn.Linear(256, 128), nn.LeakyReLU(), nn.Linear(128, 3))
    self.specie = nn.Sequential(nn.Flatten(), nn.Linear(512, 256), nn.LeakyReLU(), nn.Linear(256, 128), nn.LeakyReLU(), nn.Linear(128, 10))
    self.bbox = nn.Sequential(nn.Flatten(), nn.Linear(512, 256), nn.LeakyReLU(), nn.Linear(256, 128), nn.LeakyReLU(), nn.Linear(128, 4))
    self.avg_pool = nn.AdaptiveAvgPool2d(1)
    
    ### Initialize the required Layers
    if load_state is not None:
      self.load_state_dict(load_state)

  def forward(self, input):
      out_backbone = self.backbone(input)
      feats = self.avg_pool(out_backbone)
      ### Write Forward Calls for the Model
      object = self.have_object(feats)
      bbox =  self.bbox(feats)
      cat_or_dog = self.cat_or_dog(feats)
      specie = self.specie(feats)

      return {
          "bbox": bbox.sigmoid(),
          "object": object.sigmoid(),
          "cat_or_dog": cat_or_dog,
          "specie": specie
      }

# CUSTOM DATALOADER IMPLEMENTATION

In [76]:
train_list = np.load('/content/assessment_dataset/train_list.npy', allow_pickle=True).tolist()
val_list = np.load('/content/assessment_dataset/val_list.npy', allow_pickle=True).tolist()

In [77]:
from bs4 import BeautifulSoup

def read_xml_file(path):
    try:
      with open(path, 'r') as f:
          data = f.read()
      bs_data = BeautifulSoup(data, 'xml')
      return {
          "object": torch.ones(1),
          "cat_or_dog": bs_data.find("name").text,
          "bbox": [
              float(bs_data.find("xmin").text),
              float(bs_data.find("ymin").text),
              float(bs_data.find("xmax").text),
              float(bs_data.find("ymax").text)
              ],
          "specie": "_".join(path.split(os.sep)[-1].split("_")[:-1])
      }
    except:
      return {
          "object": torch.zeros(1),
          "cat_or_dog": "NA",
          "bbox": [0.0, 0.0, 0.0, 0.0],
          "specie": "NA"
      }

In [99]:
from PIL import Image

import torchvision.transforms as transforms
import albumentations as A
import cv2

def image_preprocess(img_path, resize_shape=(512, 512)):
  img = Image.open(img_path)
  orig_w, orig_h = img.size
  if resize_shape is not None:
    img = img.resize(resize_shape)
  return img, orig_w, orig_h

class CustomDataset(): 
  SPECIE_MAP = {
    "NA": 0,
    "Abyssinian": 1,
    "Birman": 2,
    "Persian": 3,
    "basset_hound": 4,
    "pomeranian": 5,
    "american_pit_bull_terrier": 6,
    "american_bulldog": 7,
    "beagle": 8,
    "chihuahua": 9,
  }
  CLASS_MAP = {
      "NA": 0,
      "cat": 1,
      "dog": 2
  }

  def __init__(self, dataset_path, images_list, train=False):

    self.preprocess = image_preprocess
    self.transforms = A.Compose([
      A.Resize(512, 512)] +  
      ([A.HorizontalFlip(p=0.25),
      A.ShiftScaleRotate(p=0.25),
      A.RandomBrightnessContrast(p=0.25),
    ] if train else []),
    bbox_params=A.BboxParams(format='pascal_voc', label_fields=['class_labels']),
    )
    self.image_folder_path = os.path.join(dataset_path, "images")
    label_folder_path = os.path.join(dataset_path, "labels")

    self.image_names = []
    self.processed_labels = {}

    for path in os.listdir(self.image_folder_path):
        name = path.split(os.sep)[-1].split(".")[0]
        if name in images_list:
          self.image_names.append(path)
          xml_path = os.path.join(label_folder_path, name+".xml")
          xml_data = read_xml_file(xml_path)
          self.processed_labels[path] = xml_data

  def __len__(self):
    return len(self.image_names)

  def __getitem__(self, index):
    img_name = self.image_names[index]
    label = self.processed_labels[img_name].copy()
    
    image = cv2.imread(os.path.join(self.image_folder_path, img_name))
    
    if label['object'][0] == 0:
      label['bbox'][2:] = image.shape[1::-1]

    transformed = self.transforms(image=image, bboxes=torch.tensor([label['bbox']]), class_labels=[0])
    image = transforms.ToTensor()(transformed['image'])

    label['bbox'] = torch.tensor(transformed['bboxes'][0], dtype=torch.float32) / 512
    
    label['cat_or_dog'] = self.CLASS_MAP[label['cat_or_dog']]
    label['specie'] = self.SPECIE_MAP[label['specie']]
    label['image_name'] = self.image_names[index]
    
    return image, label
  

# TRAINING LOOP IMPLEMENTATION

## Initializations

In [100]:
from torch.utils.data import DataLoader

In [101]:
# import our library
import torchmetrics
from torchmetrics.detection.mean_ap import MeanAveragePrecision
import torch.nn.functional as F
from PIL import ImageDraw
from tqdm import tqdm

def train(epochs, model_weights=None):

  # Initialize Model and Optimizer
  model = Model()
  optimizer = torch.optim.SGD(model.parameters(), lr=0.005, momentum=0.9)
  start_epoch = 0

  if torch.cuda.is_available():
    model = model.cuda()
  
  if model_weights:
    checkpoint = torch.load(model_weights)
    model.load_state_dict(checkpoint['state_dict'])
    optimizer.load_state_dict(checkpoint['optimizer'])
    start_epoch = checkpoint['epoch']
    
  if start_epoch + 1 >= epochs:
    print(f"Already trained for {start_epoch + 1} epochs")
    return

  
  
  def compute_box_loss(predictions, targets):
    return F.l1_loss(predictions, targets, reduction='none') + F.mse_loss(predictions, targets, reduction='none')
  
  # Initialize Loss Functions
  have_object_loss = nn.BCELoss()
  specie_loss = F.cross_entropy
  cat_or_dog_loss = F.cross_entropy
  bbox_loss = compute_box_loss#F.l1_loss # Not necessary you need to apply function to all coordinates together, You can have separete loss functions for all coordinates too
  # Below or Above
  # xmin_loss = nn.MSELoss()
  # ymin_loss = nn.MSELoss()
  # xmax_loss = nn.MSELoss()
  # ymax_loss = nn.MSELoss()

  training_dataset = CustomDataset(f"/content/assessment_dataset", images_list=train_list, train=True)
  training_loader = DataLoader(training_dataset, batch_size=64, shuffle=True)

  if torch.cuda.is_available():
    model = model.cuda()

  def train_one_epoch(epoch_index, tb_writer):
      running_loss = 0.
      last_loss = 0.
      mloss = torch.zeros(4)
      pbar = tqdm(training_loader)

      model.train()
      # Here, we use enumerate(training_loader) instead of
      # iter(training_loader) so that we can track the batch
      # index and do some intra-epoch reporting
      for i, data in enumerate(pbar):
          optimizer.zero_grad()
          # Every data instance is an input + label pair
          inputs, labels = data
          if torch.cuda.is_available():
            inputs = inputs.cuda()
            labels = {k: v.cuda() for k, v in labels.items() if k!='image_name'}

          # Make predictions for this batch
          outputs = model(inputs)
          # Compute the loss and its gradients
          loss_have_object = have_object_loss(outputs["object"], labels["object"])
          loss_specie = specie_loss(outputs["specie"], labels["specie"])
          loss_cat_or_dog = cat_or_dog_loss(outputs["cat_or_dog"], labels["cat_or_dog"])
          
          #ipdb.set_trace(context=6)
          loss_bbox  = ((bbox_loss(outputs["bbox"], labels["bbox"])).sum(1) * labels["object"].reshape(-1)).mean()
          loss_bbox *= 1.5 # box is weighed based on experimentations
          # Above or Below
          # loss_xmin = xmin_loss(outputs["bbox"], None)
          # loss_ymin = ymin_loss(outputs["bbox"], None)
          # loss_xmax = xmax_loss(outputs["bbox"], None)
          # loss_ymax = ymax_loss(outputs["bbox"], None)

          
          loss =  loss_have_object + loss_specie + loss_cat_or_dog + loss_bbox # Consolidate all individual losses

          loss.backward()
          optimizer.step()

          loss_items =   torch.tensor([loss_have_object.item(),  loss_specie.item(),  loss_cat_or_dog.item(),  loss_bbox.item()])         
          # Gather data and report
          running_loss += loss.item()
          mloss = (mloss * i + loss_items) / (i + 1)
          pbar.set_description(
            ("%10.4g" * 5)
              % (
                *mloss,
                 loss,
                )
          )

      return running_loss

  for i in range(start_epoch+1, epochs):

    epoch_loss = train_one_epoch(i, None)
    print(f' Epoch {i} Loss : {epoch_loss}')

    state = {
        'state_dict': model.state_dict(),
        'optimizer': optimizer.state_dict(),
        'epoch': i
    }
    torch.save(state, "model.pth")
    metrics = test(model, val_list)
    [print(k, ":\n", metric) for k, metric in metrics.items()]


def test(model, val_list):

  def post_process_object(x):
    return x

  def post_process_cat_or_dog(x):
    return x.softmax(1)

  def post_process_specie(x):
    return x.softmax(1)

  def post_process_bbox(x):
    return x*512

  val_dataset = CustomDataset(f"/content/assessment_dataset", images_list=val_list)
  val_loader = DataLoader(val_dataset, batch_size=32, shuffle=False)

  
  metric_object = torchmetrics.F1Score('binary', num_classes=1)
  metric_cat_or_dog = torchmetrics.ConfusionMatrix('multiclass', num_classes=3)
  metric_specie = torchmetrics.ConfusionMatrix('multiclass', num_classes=10)
  metric_bbox = MeanAveragePrecision()

  model.eval()
  with torch.no_grad():
    for j, data in enumerate(tqdm(val_loader)):
      inputs, labels = data

      if torch.cuda.is_available():
        inputs = inputs.cuda()
        
      # Make predictions for this batch
      outputs = model(inputs)
      # pulling everything to CPU to save GPU memory overflow
      outputs = {k: v.cpu() for k, v in outputs.items()}

      specie = post_process_specie(outputs["specie"])
      
      metric_object.update(
          post_process_object(outputs["object"]), 
          labels["object"]
      )
      metric_cat_or_dog.update(
          post_process_cat_or_dog(outputs["cat_or_dog"]), 
          labels["cat_or_dog"]
      )
      metric_specie.update(
          specie, 
          labels["specie"]
      )
      
      
      pred_boxes = post_process_bbox(outputs["bbox"])
      gt_boxes = post_process_bbox(labels["bbox"])
      pred_scores, pred_labels = specie.max(1)
      metric_bbox.update(
          preds=[
              dict(
                  boxes=pred_boxes,
                  scores=pred_scores,
                  labels=pred_labels,
              )
          ],
          target=[
            dict(
              boxes=gt_boxes,
              labels=labels["specie"],
            )
          ]
      )


    score_object = metric_object.compute()
    score_cat_or_dog = metric_cat_or_dog.compute()
    score_specie = metric_specie.compute()
    score_bbox = metric_bbox.compute()

    return {
      "F1_object": score_object, 
      "CFM_cat_or_dog": score_cat_or_dog, 
      "CFM_specie": score_specie, 
      "MAP_bbox": score_bbox
    }
    

In [107]:
from PIL import Image
import torch
import os
from pathlib import Path
import cv2

def visualize(model_weights, image_folder_path, output_folder="output"):

  object_score_threshold = 0.5

  os.makedirs(output_folder, exist_ok=True)
  model = Model(torch.load(model_weights)['state_dict'])

  if torch.cuda.is_available():
    model=model.cuda()

  model.eval()
  
  id2class = { v: k for k, v in CustomDataset.CLASS_MAP.items()}
  id2specie = { v: k for k, v in CustomDataset.SPECIE_MAP.items()}


  image_list = [Path(f).stem for f in os.listdir(image_folder_path)]
  test_dataset = CustomDataset(Path(image_folder_path).parent, images_list=image_list)
  test_loader = DataLoader(test_dataset, batch_size=4, shuffle=False)
  
  results= {}
  
  with torch.no_grad():
    for j, data in enumerate(tqdm(test_loader)):
      inputs, labels = data

      if torch.cuda.is_available():
        inputs = inputs.cuda()
        
      # Make predictions for this batch some
      outputs = model(inputs)

      outputs = {k: v.cpu() for k, v in outputs.items()}

      object_scores = outputs["object"].reshape(-1).numpy()
      
      outputs["cat_or_dog"] = outputs["cat_or_dog"].softmax(1)
      outputs["specie"] = outputs["specie"].softmax(1)
      cat_or_dog_ids = outputs["cat_or_dog"].argmax(1).numpy()
      specie_ids = outputs["specie"].argmax(1).numpy()

      for i in range(inputs.shape[0]):
        
        
        image, orig_w, orig_h = image_preprocess(os.path.join(image_folder_path, labels['image_name'][i]), resize_shape=None)
        image = np.array(image)
        
        image_result = {
            "has_object": object_scores[i] > object_score_threshold,
            "cat_or_dog": id2class[cat_or_dog_ids[i]],
            "specie": id2specie[specie_ids[i]],
        }

        if image_result['has_object']:
          box = outputs["bbox"][i].numpy() * np.array([orig_w, orig_h, orig_w, orig_h])
        else:
          box = np.zeros(4)

        image_result.update(
            {
              "xmin": box[0],
              "ymin": box[1],
              "xmax": box[2],
              "ymax": box[3]
            }
        )
          
        text = "object={:.2f}, {}:{:.2f} ({}:{:.2f})".format(
          image_result['has_object'],
          image_result['cat_or_dog'],
          outputs["cat_or_dog"][i][cat_or_dog_ids[i]],
          image_result['specie'],
          outputs["specie"][i][specie_ids[i]],
        )
        
        image = cv2.putText(image, text, (10,20), cv2.FONT_HERSHEY_SIMPLEX, 
                  0.5, (50,255,50), 1)
        pt1 = box[:2].astype(int)
        pt2 = box[2:].astype(int)
        image = cv2.rectangle(image, pt1, pt2, (0,0,255), 1)
          

        Image.fromarray(image).save(os.path.join(output_folder, labels['image_name'][i]))
        results[labels['image_name'][i]] = image_result   

  return results

In [103]:
train(15)

    0.5809     2.285    0.9995      1.17     4.494: 100%|██████████| 13/13 [00:20<00:00,  1.56s/it]


 Epoch 1 Loss : 65.46617078781128


100%|██████████| 7/7 [00:02<00:00,  2.45it/s]


F1_object :
 tensor(0.9222)
CFM_cat_or_dog :
 tensor([[  0,   0,  28],
        [  0,   0,  51],
        [  0,   0, 115]])
CFM_specie :
 tensor([[28,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [17,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [19,  0,  1,  0,  0,  0,  0,  0,  0,  0],
        [13,  0,  1,  0,  0,  0,  0,  0,  0,  0],
        [18,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [23,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [17,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [20,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [20,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [17,  0,  0,  0,  0,  0,  0,  0,  0,  0]])
MAP_bbox :
 {'map': tensor(0.0103), 'map_50': tensor(0.0468), 'map_75': tensor(0.0109), 'map_small': tensor(-1.), 'map_medium': tensor(0.), 'map_large': tensor(0.0109), 'mar_1': tensor(0.0067), 'mar_10': tensor(0.0146), 'mar_100': tensor(0.0181), 'mar_small': tensor(-1.), 'mar_medium': tensor(0.), 'mar_large': tensor(0.0192), 'map_per_class': tensor(-1.), 'mar_

    0.3748     2.205    0.8515    0.7921     4.082: 100%|██████████| 13/13 [00:19<00:00,  1.48s/it]


 Epoch 2 Loss : 54.905818939208984


100%|██████████| 7/7 [00:02<00:00,  2.55it/s]


F1_object :
 tensor(0.9222)
CFM_cat_or_dog :
 tensor([[  0,   0,  28],
        [  0,  33,  18],
        [  0,   3, 112]])
CFM_specie :
 tensor([[28,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [13,  0,  3,  0,  1,  0,  0,  0,  0,  0],
        [ 2,  0, 15,  3,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  9,  5,  0,  0,  0,  0,  0,  0],
        [15,  0,  0,  0,  3,  0,  0,  0,  0,  0],
        [15,  0,  0,  6,  0,  1,  0,  0,  0,  1],
        [14,  0,  0,  0,  1,  0,  2,  0,  0,  0],
        [ 8,  0,  0,  0,  3,  0,  0,  9,  0,  0],
        [15,  0,  0,  1,  4,  0,  0,  0,  0,  0],
        [14,  0,  0,  0,  0,  0,  1,  0,  0,  2]])
MAP_bbox :
 {'map': tensor(0.0445), 'map_50': tensor(0.1171), 'map_75': tensor(0.0173), 'map_small': tensor(-1.), 'map_medium': tensor(0.), 'map_large': tensor(0.0474), 'mar_1': tensor(0.0420), 'mar_10': tensor(0.0575), 'mar_100': tensor(0.0596), 'mar_small': tensor(-1.), 'mar_medium': tensor(0.), 'mar_large': tensor(0.0634), 'map_per_class': tensor(-1.), 'mar_

    0.2763     2.057    0.6102    0.6931     3.617: 100%|██████████| 13/13 [00:19<00:00,  1.48s/it]


 Epoch 3 Loss : 47.27197861671448


100%|██████████| 7/7 [00:02<00:00,  2.85it/s]


F1_object :
 tensor(0.9222)
CFM_cat_or_dog :
 tensor([[  0,   4,  24],
        [  0,  48,   3],
        [  0,   6, 109]])
CFM_specie :
 tensor([[27,  0,  0,  0,  1,  0,  0,  0,  0,  0],
        [ 1,  0,  3,  7,  4,  0,  0,  0,  0,  2],
        [ 1,  0, 17,  2,  0,  0,  0,  0,  0,  0],
        [ 0,  0, 14,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0, 18,  0,  0,  0,  0,  0],
        [ 0,  0,  1,  5,  0,  6,  1,  0,  0, 10],
        [ 0,  0,  0,  0,  4,  0, 13,  0,  0,  0],
        [ 0,  0,  0,  0,  8,  0,  1, 11,  0,  0],
        [ 0,  0,  0,  0, 20,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  1,  0, 12,  0,  0,  4]])
MAP_bbox :
 {'map': tensor(0.0620), 'map_50': tensor(0.2127), 'map_75': tensor(0.0226), 'map_small': tensor(-1.), 'map_medium': tensor(0.), 'map_large': tensor(0.0652), 'mar_1': tensor(0.0520), 'mar_10': tensor(0.0888), 'mar_100': tensor(0.0922), 'mar_small': tensor(-1.), 'mar_medium': tensor(0.), 'mar_large': tensor(0.0972), 'map_per_class': tensor(-1.), 'mar_

    0.2004     1.732    0.3637    0.6529     2.653: 100%|██████████| 13/13 [00:19<00:00,  1.50s/it]


 Epoch 4 Loss : 38.34070181846619


100%|██████████| 7/7 [00:02<00:00,  2.86it/s]


F1_object :
 tensor(0.9222)
CFM_cat_or_dog :
 tensor([[  4,   4,  20],
        [  0,  48,   3],
        [  0,   4, 111]])
CFM_specie :
 tensor([[26,  0,  0,  0,  2,  0,  0,  0,  0,  0],
        [ 0,  3,  0, 10,  2,  0,  0,  0,  0,  2],
        [ 1,  0,  3, 16,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0, 14,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0, 18,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  5,  0, 13,  0,  0,  0,  5],
        [ 0,  0,  0,  0,  4,  0, 13,  0,  0,  0],
        [ 0,  0,  0,  0,  8,  0,  1, 11,  0,  0],
        [ 0,  0,  0,  1, 19,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  1,  0,  8,  1,  0,  7]])
MAP_bbox :
 {'map': tensor(0.0888), 'map_50': tensor(0.2711), 'map_75': tensor(0.0341), 'map_small': tensor(-1.), 'map_medium': tensor(0.), 'map_large': tensor(0.0921), 'mar_1': tensor(0.0633), 'mar_10': tensor(0.1117), 'mar_100': tensor(0.1156), 'mar_small': tensor(-1.), 'mar_medium': tensor(0.), 'mar_large': tensor(0.1198), 'map_per_class': tensor(-1.), 'mar_

     0.159     1.287    0.2341    0.6239     2.289: 100%|██████████| 13/13 [00:19<00:00,  1.48s/it]


 Epoch 5 Loss : 29.947426557540894


100%|██████████| 7/7 [00:02<00:00,  2.92it/s]


F1_object :
 tensor(0.9326)
CFM_cat_or_dog :
 tensor([[ 17,   1,  10],
        [  0,  47,   4],
        [  0,   0, 115]])
CFM_specie :
 tensor([[24,  1,  0,  0,  0,  0,  0,  2,  0,  1],
        [ 0, 13,  1,  0,  0,  3,  0,  0,  0,  0],
        [ 1,  0, 18,  1,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  4,  9,  0,  1,  0,  0,  0,  0],
        [ 0,  0,  0,  0, 14,  0,  0,  1,  3,  0],
        [ 0,  0,  0,  2,  0, 21,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  2,  0,  2,  2,  0, 11],
        [ 0,  0,  0,  0,  0,  0,  1, 19,  0,  0],
        [ 0,  0,  0,  0, 10,  0,  2,  2,  6,  0],
        [ 0,  0,  0,  0,  0,  2,  0,  1,  0, 14]])
MAP_bbox :
 {'map': tensor(0.0889), 'map_50': tensor(0.2861), 'map_75': tensor(0.0281), 'map_small': tensor(-1.), 'map_medium': tensor(0.), 'map_large': tensor(0.0933), 'mar_1': tensor(0.0601), 'mar_10': tensor(0.1211), 'mar_100': tensor(0.1211), 'mar_small': tensor(-1.), 'mar_medium': tensor(0.), 'mar_large': tensor(0.1268), 'map_per_class': tensor(-1.), 'mar_

    0.1188    0.9203    0.1259    0.6044     1.843: 100%|██████████| 13/13 [00:19<00:00,  1.51s/it]


 Epoch 6 Loss : 23.002904415130615


100%|██████████| 7/7 [00:02<00:00,  2.93it/s]


F1_object :
 tensor(0.9794)
CFM_cat_or_dog :
 tensor([[ 26,   0,   2],
        [  1,  50,   0],
        [  3,   1, 111]])
CFM_specie :
 tensor([[27,  0,  0,  0,  1,  0,  0,  0,  0,  0],
        [ 1, 16,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0, 10,  7,  3,  0,  0,  0,  0,  0,  0],
        [ 0,  6,  0,  8,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0, 18,  0,  0,  0,  0,  0],
        [ 0,  3,  0,  2,  0, 16,  0,  0,  0,  2],
        [ 0,  1,  0,  0,  3,  0, 13,  0,  0,  0],
        [ 1,  0,  0,  0,  3,  0,  3, 13,  0,  0],
        [ 2,  1,  0,  0, 14,  0,  2,  0,  1,  0],
        [ 1,  2,  0,  0,  0,  0,  6,  1,  0,  7]])
MAP_bbox :
 {'map': tensor(0.0821), 'map_50': tensor(0.2423), 'map_75': tensor(0.0179), 'map_small': tensor(-1.), 'map_medium': tensor(0.), 'map_large': tensor(0.0862), 'mar_1': tensor(0.0602), 'mar_10': tensor(0.1109), 'mar_100': tensor(0.1115), 'mar_small': tensor(-1.), 'mar_medium': tensor(0.), 'mar_large': tensor(0.1170), 'map_per_class': tensor(-1.), 'mar_

   0.08488    0.7078    0.0676    0.5899     1.406: 100%|██████████| 13/13 [00:18<00:00,  1.44s/it]


 Epoch 7 Loss : 18.852532386779785


100%|██████████| 7/7 [00:03<00:00,  2.18it/s]


F1_object :
 tensor(0.9852)
CFM_cat_or_dog :
 tensor([[ 24,   0,   4],
        [  1,  49,   1],
        [  0,   0, 115]])
CFM_specie :
 tensor([[25,  1,  0,  0,  0,  0,  0,  1,  0,  1],
        [ 0, 16,  0,  0,  0,  0,  0,  0,  0,  1],
        [ 0,  1, 18,  1,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  1, 12,  0,  1,  0,  0,  0,  0],
        [ 0,  0,  0,  0, 13,  0,  0,  3,  2,  0],
        [ 0,  0,  0,  1,  0, 22,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  1,  0,  7,  2,  0,  7],
        [ 0,  0,  0,  0,  0,  0,  2, 17,  1,  0],
        [ 2,  1,  0,  0,  3,  0,  2,  1, 11,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  1,  0, 16]])
MAP_bbox :
 {'map': tensor(0.1119), 'map_50': tensor(0.3216), 'map_75': tensor(0.0479), 'map_small': tensor(-1.), 'map_medium': tensor(0.), 'map_large': tensor(0.1173), 'mar_1': tensor(0.0768), 'mar_10': tensor(0.1441), 'mar_100': tensor(0.1441), 'mar_small': tensor(-1.), 'mar_medium': tensor(0.), 'mar_large': tensor(0.1513), 'map_per_class': tensor(-1.), 'mar_

   0.05919    0.5682   0.03409    0.5761    0.9878: 100%|██████████| 13/13 [00:19<00:00,  1.51s/it]


 Epoch 8 Loss : 16.08943283557892


100%|██████████| 7/7 [00:02<00:00,  2.74it/s]


F1_object :
 tensor(0.9910)
CFM_cat_or_dog :
 tensor([[ 25,   1,   2],
        [  0,  51,   0],
        [  0,   3, 112]])
CFM_specie :
 tensor([[26,  1,  0,  0,  0,  0,  0,  1,  0,  0],
        [ 0, 17,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  3, 13,  4,  0,  0,  0,  0,  0,  0],
        [ 0,  1,  0, 12,  0,  1,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  1, 17,  0],
        [ 0,  0,  0,  1,  0, 22,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  1,  5,  2,  1,  8],
        [ 1,  0,  0,  0,  0,  0,  1, 13,  4,  1],
        [ 1,  1,  0,  0,  0,  1,  0,  0, 15,  2],
        [ 0,  0,  0,  0,  0,  2,  0,  1,  0, 14]])
MAP_bbox :
 {'map': tensor(0.0794), 'map_50': tensor(0.2617), 'map_75': tensor(0.0329), 'map_small': tensor(-1.), 'map_medium': tensor(0.), 'map_large': tensor(0.0837), 'mar_1': tensor(0.0586), 'mar_10': tensor(0.1145), 'mar_100': tensor(0.1145), 'mar_small': tensor(-1.), 'mar_medium': tensor(0.), 'mar_large': tensor(0.1205), 'map_per_class': tensor(-1.), 'mar_

   0.03777    0.4509   0.02148    0.5658    0.9385: 100%|██████████| 13/13 [00:19<00:00,  1.50s/it]


 Epoch 9 Loss : 13.987280309200287


100%|██████████| 7/7 [00:02<00:00,  2.92it/s]


F1_object :
 tensor(0.9880)
CFM_cat_or_dog :
 tensor([[ 26,   0,   2],
        [  1,  50,   0],
        [  1,   0, 114]])
CFM_specie :
 tensor([[26,  1,  0,  0,  0,  0,  0,  0,  1,  0],
        [ 0, 15,  0,  0,  0,  0,  0,  0,  0,  2],
        [ 0,  5, 14,  1,  0,  0,  0,  0,  0,  0],
        [ 0,  8,  0,  5,  0,  0,  0,  0,  0,  1],
        [ 0,  0,  0,  0,  7,  0,  0,  0, 11,  0],
        [ 0,  0,  0,  0,  0,  7,  0,  0,  0, 16],
        [ 0,  0,  0,  0,  1,  0,  2,  1,  0, 13],
        [ 1,  0,  0,  0,  0,  0,  9,  4,  3,  3],
        [ 3,  0,  0,  0,  1,  0,  1,  0, 13,  2],
        [ 0,  0,  0,  0,  0,  0,  0,  1,  0, 16]])
MAP_bbox :
 {'map': tensor(0.0453), 'map_50': tensor(0.1136), 'map_75': tensor(0.0219), 'map_small': tensor(-1.), 'map_medium': tensor(0.), 'map_large': tensor(0.0488), 'mar_1': tensor(0.0386), 'mar_10': tensor(0.0690), 'mar_100': tensor(0.0690), 'mar_small': tensor(-1.), 'mar_medium': tensor(0.), 'mar_large': tensor(0.0736), 'map_per_class': tensor(-1.), 'mar_

   0.02168    0.3697   0.01777    0.5479    0.9808: 100%|██████████| 13/13 [00:19<00:00,  1.49s/it]


 Epoch 10 Loss : 12.44229793548584


100%|██████████| 7/7 [00:02<00:00,  2.88it/s]


F1_object :
 tensor(0.9910)
CFM_cat_or_dog :
 tensor([[ 25,   0,   3],
        [  1,  49,   1],
        [  0,   1, 114]])
CFM_specie :
 tensor([[25,  0,  0,  0,  0,  0,  0,  1,  2,  0],
        [ 1, 15,  0,  1,  0,  0,  0,  0,  0,  0],
        [ 0,  1, 17,  2,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  2, 12,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0, 12,  0,  0,  1,  5,  0],
        [ 0,  0,  0,  1,  0, 21,  0,  0,  0,  1],
        [ 0,  0,  0,  0,  1,  0,  9,  2,  0,  5],
        [ 0,  0,  0,  0,  0,  0,  0, 20,  0,  0],
        [ 1,  0,  0,  0,  2,  0,  0,  1, 16,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  1,  0, 16]])
MAP_bbox :
 {'map': tensor(0.1121), 'map_50': tensor(0.3526), 'map_75': tensor(0.0514), 'map_small': tensor(-1.), 'map_medium': tensor(0.), 'map_large': tensor(0.1168), 'mar_1': tensor(0.0701), 'mar_10': tensor(0.1540), 'mar_100': tensor(0.1540), 'mar_small': tensor(-1.), 'mar_medium': tensor(0.), 'mar_large': tensor(0.1617), 'map_per_class': tensor(-1.), 'mar_

   0.01767    0.2805   0.01624    0.5424    0.8158: 100%|██████████| 13/13 [00:19<00:00,  1.48s/it]


 Epoch 11 Loss : 11.13950490951538


100%|██████████| 7/7 [00:02<00:00,  2.88it/s]


F1_object :
 tensor(0.9881)
CFM_cat_or_dog :
 tensor([[ 25,   0,   3],
        [  1,  48,   2],
        [  0,   1, 114]])
CFM_specie :
 tensor([[25,  0,  0,  0,  0,  0,  0,  0,  3,  0],
        [ 1, 15,  0,  0,  0,  0,  0,  0,  1,  0],
        [ 0,  0, 19,  0,  0,  0,  0,  0,  1,  0],
        [ 0,  1,  3, 10,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0, 12,  0,  0,  0,  6,  0],
        [ 0,  1,  0,  0,  0, 17,  0,  0,  0,  5],
        [ 0,  0,  0,  0,  1,  0,  6,  1,  2,  7],
        [ 0,  0,  0,  0,  0,  0,  0, 15,  5,  0],
        [ 0,  0,  0,  0,  1,  0,  0,  0, 19,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  1, 16]])
MAP_bbox :
 {'map': tensor(0.0953), 'map_50': tensor(0.2728), 'map_75': tensor(0.0345), 'map_small': tensor(-1.), 'map_medium': tensor(0.), 'map_large': tensor(0.1003), 'mar_1': tensor(0.0706), 'mar_10': tensor(0.1332), 'mar_100': tensor(0.1337), 'mar_small': tensor(-1.), 'mar_medium': tensor(0.), 'mar_large': tensor(0.1405), 'map_per_class': tensor(-1.), 'mar_

   0.01585    0.2142   0.01395    0.5398    0.6728: 100%|██████████| 13/13 [00:18<00:00,  1.46s/it]


 Epoch 12 Loss : 10.18945324420929


100%|██████████| 7/7 [00:02<00:00,  2.50it/s]


F1_object :
 tensor(0.9881)
CFM_cat_or_dog :
 tensor([[ 25,   0,   3],
        [  1,  49,   1],
        [  0,   1, 114]])
CFM_specie :
 tensor([[26,  0,  0,  0,  0,  0,  0,  0,  2,  0],
        [ 0, 15,  0,  0,  0,  0,  0,  0,  0,  2],
        [ 0,  0, 20,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  1,  3, 10,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  7,  0,  0,  2,  9,  0],
        [ 0,  0,  0,  0,  0, 21,  0,  0,  0,  2],
        [ 0,  0,  0,  0,  1,  0, 12,  2,  0,  2],
        [ 0,  0,  0,  0,  0,  0,  0, 19,  1,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  2, 18,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  1,  0, 16]])
MAP_bbox :
 {'map': tensor(0.1089), 'map_50': tensor(0.3168), 'map_75': tensor(0.0504), 'map_small': tensor(-1.), 'map_medium': tensor(0.), 'map_large': tensor(0.1146), 'mar_1': tensor(0.0704), 'mar_10': tensor(0.1498), 'mar_100': tensor(0.1498), 'mar_small': tensor(-1.), 'mar_medium': tensor(0.), 'mar_large': tensor(0.1576), 'map_per_class': tensor(-1.), 'mar_

   0.01023    0.2083  0.009791    0.5359     0.951: 100%|██████████| 13/13 [00:18<00:00,  1.45s/it]


 Epoch 13 Loss : 9.93429982662201


100%|██████████| 7/7 [00:02<00:00,  2.63it/s]


F1_object :
 tensor(0.9910)
CFM_cat_or_dog :
 tensor([[ 26,   0,   2],
        [  1,  50,   0],
        [  1,   1, 113]])
CFM_specie :
 tensor([[27,  0,  0,  0,  0,  0,  0,  1,  0,  0],
        [ 1, 15,  0,  1,  0,  0,  0,  0,  0,  0],
        [ 0,  0, 18,  2,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0, 14,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0, 12,  0,  0,  0,  6,  0],
        [ 0,  0,  0,  0,  0, 23,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  1,  0, 13,  2,  0,  1],
        [ 0,  0,  0,  0,  0,  0,  0, 20,  0,  0],
        [ 1,  0,  0,  0,  0,  0,  0,  0, 19,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  1, 16]])
MAP_bbox :
 {'map': tensor(0.1264), 'map_50': tensor(0.3861), 'map_75': tensor(0.0619), 'map_small': tensor(-1.), 'map_medium': tensor(0.), 'map_large': tensor(0.1312), 'mar_1': tensor(0.0770), 'mar_10': tensor(0.1776), 'mar_100': tensor(0.1776), 'mar_small': tensor(-1.), 'mar_medium': tensor(0.), 'mar_large': tensor(0.1851), 'map_per_class': tensor(-1.), 'mar_

   0.01068    0.1816   0.01198    0.5316    0.8353: 100%|██████████| 13/13 [00:19<00:00,  1.47s/it]


 Epoch 14 Loss : 9.566650152206421


100%|██████████| 7/7 [00:02<00:00,  2.84it/s]


F1_object :
 tensor(0.9881)
CFM_cat_or_dog :
 tensor([[ 24,   1,   3],
        [  1,  50,   0],
        [  0,   1, 114]])
CFM_specie :
 tensor([[25,  0,  0,  0,  0,  0,  0,  1,  2,  0],
        [ 1, 15,  0,  1,  0,  0,  0,  0,  0,  0],
        [ 0,  0, 19,  1,  0,  0,  0,  0,  0,  0],
        [ 0,  1,  0, 13,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  7,  0,  0,  0, 11,  0],
        [ 0,  1,  0,  1,  0, 18,  0,  0,  0,  3],
        [ 0,  0,  0,  0,  1,  0, 11,  2,  0,  3],
        [ 0,  0,  0,  0,  0,  0,  0, 18,  2,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0, 20,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  1, 16]])
MAP_bbox :
 {'map': tensor(0.1208), 'map_50': tensor(0.3552), 'map_75': tensor(0.0490), 'map_small': tensor(-1.), 'map_medium': tensor(0.), 'map_large': tensor(0.1263), 'mar_1': tensor(0.0687), 'mar_10': tensor(0.1664), 'mar_100': tensor(0.1664), 'mar_small': tensor(-1.), 'mar_medium': tensor(0.), 'mar_large': tensor(0.1748), 'map_per_class': tensor(-1.), 'mar_

In [104]:
train(11, 'model.pth')

Already trained for 15 epochs


In [109]:
results = visualize('model.pth', '/content/assessment_dataset/images')

100%|██████████| 247/247 [00:26<00:00,  9.47it/s]
